### ISSUE TITLE
heroku input finishes randomly

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-input-heroku#3]
(This issue was originally filed by @gauravarora at https://github.com/elastic/logstash-contrib/issues/39)

---

I recently installed logstash to get logs from a couple of heroku apps. The problem is that the heroku input closes randomly. This causes the logstash instance to stop because I have only one input configured.

This problem is visible not just with the logstash contrib plugin but can also be observed using the heroku toolbelt so this is not the input's fault. I added a simple solution to my local contrib installation by wrapping the log tailing in the heroku input in a while loop.

I would like to ask if this is a valid solution and if yes then I will submit a PR for this fix.

**Comment by wiibaa** [comment]
@jordansissel @suyograo Dup of #1
